name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Login to the docker cli
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      # run tests
      - run: docker build -t m971119/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true m971119/react-test npm test
 
      # build images
      - run: docker build -t m971119/multi-client-10-14 ./client
      - run: docker build -t m971119/multi-nginx-10-14 ./nginx
      - run: docker build -t m971119/multi-server-10-14 ./server
      - run: docker build -t m971119/multi-worker-10-14 ./worker
 
      # Take the images and push them to docker hub
      - run: docker push m971119/multi-client-10-14
      - run: docker push m971119/multi-nginx-10-14
      - run: docker push m971119/multi-server-10-14
      - run: docker push m971119/multi-worker-10-14